import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const PLUGIN_PATH = '.opencode/plugins/pm.ts'
const CONFIG_PATH = 'opencode.json'
const PLUGIN_ENTRY = './.opencode/plugins/pm.ts'

/** Generate the OpenCode plugin file and register it in opencode.json.
 *  Returns 'added', 'updated', or 'exists'.
 *  When `force` is true, always rewrite even if content matches. */
export function ensureOpenCodePlugin(cwd: string, force = false): 'added' | 'updated' | 'exists' {
  const pluginDir = join(cwd, '.opencode', 'plugins')
  const pluginFile = join(cwd, PLUGIN_PATH)

  if (!existsSync(pluginDir)) mkdirSync(pluginDir, { recursive: true })

  const content = generatePluginContent()
  let result: 'added' | 'updated' | 'exists'

  if (existsSync(pluginFile)) {
    const existing = readFileSync(pluginFile, 'utf-8')
    if (!force && existing === content) {
      result = 'exists'
    } else {
      writeFileSync(pluginFile, content)
      result = 'updated'
    }
  } else {
    writeFileSync(pluginFile, content)
    result = 'added'
  }

  ensureOpenCodeConfig(cwd)
  return result
}

/** Ensure opencode.json exists and includes the pm plugin entry. */
function ensureOpenCodeConfig(cwd: string) {
  const configFile = join(cwd, CONFIG_PATH)
  let config: Record<string, unknown> = {}

  if (existsSync(configFile)) {
    try {
      config = JSON.parse(readFileSync(configFile, 'utf-8'))
    } catch {
      // Malformed JSON — overwrite
      config = {}
    }
  }

  const plugins: string[] = Array.isArray(config.plugin) ? config.plugin : []

  if (!plugins.includes(PLUGIN_ENTRY)) {
    plugins.push(PLUGIN_ENTRY)
    config.plugin = plugins
    writeFileSync(configFile, JSON.stringify(config, null, 2) + '\n')
  }
}

/** Check if OpenCode plugin is already installed. */
export function hasOpenCodePlugin(cwd: string): boolean {
  return existsSync(join(cwd, PLUGIN_PATH))
}

function generatePluginContent(): string {
  return `// pm — project manager plugin for OpenCode
// Auto-generated by: pm init --opencode
// Do not edit manually — re-run pm init --opencode to update.

export const PmPlugin = async ({ client, $, directory }) => {
  // Use process.pid as instance identity — unique per OpenCode session
  const agent = "opencode"
  const instance = String(process.pid)

  const log = (level, message, extra) =>
    client.app.log({ body: { service: "pm", level, message, ...extra && { extra } } }).catch(() => {})

  // Session start: cleanup stuck tasks and show briefing
  try {
    await $\`pm cleanup --quiet --agent \${agent} --instance \${instance}\`.cwd(directory).quiet()
    const recap = await $\`pm recap --brief --agent \${agent} --instance \${instance}\`.cwd(directory).text()
    if (recap.trim()) {
      await log("info", recap.trim())
    }
  } catch (err) {
    await log("warn", "pm session start failed", { error: String(err) })
  }

  // Helper to check if a file path is a pm/config file (always allowed)
  const isConfigFile = (filePath) =>
    filePath.includes(".pm/") ||
    filePath.includes(".claude/") ||
    filePath.includes(".opencode/") ||
    filePath.endsWith("CLAUDE.md") ||
    filePath.includes("/memory/")

  return {
    // Block edits without active work (mirrors Claude Code PreToolUse hook)
    "tool.execute.before": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      if (isConfigFile(filePath)) return

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      const result = await $\`echo \${stdin} | pm hook pre-edit --agent \${agent} --instance \${instance}\`
        .cwd(directory)
        .nothrow()
        .quiet()
      if (result.exitCode === 2) {
        throw new Error(
          "No active task in pm. Run pm add-issue or pm add-feature first."
        )
      }
    },

    // Track file edits (mirrors Claude Code PostToolUse hook)
    "tool.execute.after": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      if (!filePath || isConfigFile(filePath)) return

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      await $\`echo \${stdin} | pm hook post-edit --agent \${agent} --instance \${instance}\`
        .cwd(directory)
        .nothrow()
        .quiet()
    },

    // Inject task context into prompts (mirrors Claude Code UserPromptSubmit hook)
    "tui.prompt.append": async (_input, output) => {
      try {
        const summary = await $\`pm hook prompt-context --agent \${agent} --instance \${instance}\`
          .cwd(directory)
          .text()
        if (summary.trim()) {
          output.parts = output.parts ?? []
          output.parts.push({ type: "text", text: summary.trim() })
        }
      } catch {}
    },

    // Track session lifecycle events
    event: async ({ event }) => {
      if (event.type === "session.created") {
        await log("info", "Session started", { sessionId: event.properties?.id })
      }
    },
  }
}
`
}
