import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const PLUGIN_PATH = '.opencode/plugins/pm.ts'

/** Generate the OpenCode plugin file. Returns 'added', 'updated', or 'exists'.
 *  When `force` is true, always rewrite even if content matches. */
export function ensureOpenCodePlugin(cwd: string, force = false): 'added' | 'updated' | 'exists' {
  const pluginDir = join(cwd, '.opencode', 'plugins')
  const pluginFile = join(cwd, PLUGIN_PATH)

  if (!existsSync(pluginDir)) mkdirSync(pluginDir, { recursive: true })

  const content = generatePluginContent()

  if (existsSync(pluginFile)) {
    const existing = readFileSync(pluginFile, 'utf-8')
    if (!force && existing === content) return 'exists'
    writeFileSync(pluginFile, content)
    return 'updated'
  }

  writeFileSync(pluginFile, content)
  return 'added'
}

/** Check if OpenCode plugin is already installed. */
export function hasOpenCodePlugin(cwd: string): boolean {
  return existsSync(join(cwd, PLUGIN_PATH))
}

function generatePluginContent(): string {
  return `// pm — project manager plugin for OpenCode
// Auto-generated by: pm init --opencode
// Do not edit manually — re-run pm init --opencode to update.

export const PmPlugin = async ({ $, directory }) => {
  // Use process.pid as instance identity — unique per OpenCode session
  const instanceId = String(process.pid)
  const agentFlags = \`--agent opencode --instance \${instanceId}\`

  // Capture model identity if available — scoped by instance so concurrent agents don't clash
  const model = process.env.PM_MODEL ?? ""
  if (model) {
    const { writeFileSync, mkdirSync, existsSync } = await import("node:fs")
    const { join } = await import("node:path")
    const pmDir = join(directory, ".pm")
    if (!existsSync(pmDir)) mkdirSync(pmDir, { recursive: true })
    writeFileSync(join(pmDir, \`model-\${instanceId}\`), model)
  }

  // Session start: cleanup stuck tasks and show briefing
  try {
    await $\`pm cleanup --quiet\`.cwd(directory).quiet()
    const recap = await $\`pm recap --brief\`.cwd(directory).text()
    if (recap.trim()) {
      console.log("[pm]", recap.trim())
    }
  } catch {}

  return {
    // Block edits without active work (mirrors Claude Code PreToolUse hook)
    "tool.execute.before": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      // Allow pm's own files and config files
      if (
        filePath.includes(".pm/") ||
        filePath.includes(".claude/") ||
        filePath.includes(".opencode/") ||
        filePath.endsWith("CLAUDE.md") ||
        filePath.includes("/memory/")
      ) {
        return
      }

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      const result = await $\`echo \${stdin} | pm hook pre-edit \${agentFlags}\`
        .cwd(directory)
        .nothrow()
        .quiet()
      if (result.exitCode === 2) {
        throw new Error(
          "No active task in pm. Run pm add-issue or pm add-feature first."
        )
      }
    },

    // Track file edits (mirrors Claude Code PostToolUse hook)
    "tool.execute.after": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      if (
        !filePath ||
        filePath.includes(".pm/") ||
        filePath.includes(".claude/") ||
        filePath.includes(".opencode/") ||
        filePath.endsWith("CLAUDE.md") ||
        filePath.includes("/memory/")
      ) {
        return
      }

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      await $\`echo \${stdin} | pm hook post-edit \${agentFlags}\`
        .cwd(directory)
        .nothrow()
        .quiet()
    },

    // Inject task context into prompts (mirrors Claude Code UserPromptSubmit hook)
    "tui.prompt.append": async (_input, output) => {
      try {
        const summary = await $\`pm hook prompt-context \${agentFlags}\`
          .cwd(directory)
          .text()
        if (summary.trim()) {
          output.parts = output.parts ?? []
          output.parts.push({ type: "text", text: summary.trim() })
        }
      } catch {}
    },
  }
}
`
}
