// pm — project manager plugin for OpenCode
// Auto-generated by: pm init --opencode
// Do not edit manually — re-run pm init --opencode to update.

export const PmPlugin = async ({ client, $, directory }) => {
  // Use process.pid as instance identity — unique per OpenCode session
  const agent = "opencode"
  const instance = String(process.pid)

  const log = (level, message, extra) =>
    client.app.log({ body: { service: "pm", level, message, ...extra && { extra } } }).catch(() => {})

  // Session start: cleanup stuck tasks and show briefing
  try {
    await $`pm cleanup --quiet --agent ${agent} --instance ${instance}`.cwd(directory).quiet()
    const recap = await $`pm recap --brief --agent ${agent} --instance ${instance}`.cwd(directory).text()
    if (recap.trim()) {
      await log("info", recap.trim())
    }
  } catch (err) {
    await log("warn", "pm session start failed", { error: String(err) })
  }

  // Helper to check if a file path is a pm/config file (always allowed)
  const isConfigFile = (filePath) =>
    filePath.includes(".pm/") ||
    filePath.includes(".claude/") ||
    filePath.includes(".opencode/") ||
    filePath.endsWith("CLAUDE.md") ||
    filePath.includes("/memory/")

  return {
    // Block edits without active work (mirrors Claude Code PreToolUse hook)
    "tool.execute.before": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      if (isConfigFile(filePath)) return

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      const result = await $`echo ${stdin} | pm hook pre-edit --agent ${agent} --instance ${instance}`
        .cwd(directory)
        .nothrow()
        .quiet()
      if (result.exitCode === 2) {
        throw new Error(
          "No active task in pm. Run pm add-issue or pm add-feature first."
        )
      }
    },

    // Track file edits (mirrors Claude Code PostToolUse hook)
    "tool.execute.after": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (tool !== "edit" && tool !== "write") return

      const filePath = output.args?.filePath ?? output.args?.file_path ?? ""
      if (!filePath || isConfigFile(filePath)) return

      const stdin = JSON.stringify({ tool_input: { file_path: filePath } })
      await $`echo ${stdin} | pm hook post-edit --agent ${agent} --instance ${instance}`
        .cwd(directory)
        .nothrow()
        .quiet()
    },

    // Inject task context into prompts (mirrors Claude Code UserPromptSubmit hook)
    "tui.prompt.append": async (_input, output) => {
      try {
        const summary = await $`pm hook prompt-context --agent ${agent} --instance ${instance}`
          .cwd(directory)
          .text()
        if (summary.trim()) {
          output.parts = output.parts ?? []
          output.parts.push({ type: "text", text: summary.trim() })
        }
      } catch {}
    },

    // Track session lifecycle events
    event: async ({ event }) => {
      if (event.type === "session.created") {
        await log("info", "Session started", { sessionId: event.properties?.id })
      }
    },
  }
}
